# Generated by Django 4.0.2 on 2022-02-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ('-episode',)},
        ),
    ]
