# Generated by Django 4.0.2 on 2022-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_podcast_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ('-date_of_release',)},
        ),
        migrations.AddField(
            model_name='release',
            name='date_of_release',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
