# Generated by Django 4.0.2 on 2022-02-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_release_date_of_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='release',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.release'),
        ),
    ]
